### ISSUE TITLE
If you get media, get an error

### ISSUE THREAD

**Issue by as1543100166** [arshamalh/twigo#8]
```
	params := twigo.Map{"expansions": "attachments.media_keys", "media.fields": "url"}
	response, err := client.GetTweet("1529097667858546689", params)
	if err != nil {
		log.Error(err)
	}
```

`json: cannot unmarshal object into Go struct field Tweet.Data.attachments of type []map[string]string `

**Comment by arshamalh** [comment]
Thanks for your attention and time, 
I just fixed the problem.

**Comment by arshamalh** [comment]
https://github.com/arshamalh/twigo/pull/10
